using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class UnitStaticsDetailedBattlePopUp : MonoBehaviour
{
    [SerializeField] public UnitIcon unitIcon;
    [SerializeField] public Text unitName;
    [SerializeField] public Text KOs;
    [SerializeField] public Text faints;
    [SerializeField] public Text debuffsApplied;
    [SerializeField] public Text buffsApplied;
    [SerializeField] public Text debuffsRecieved;
    [SerializeField] public Text buffsRecieved;
    [SerializeField] public Text totalDamageDealt;
    [SerializeField] public Text totalAttacksDealt;
    [SerializeField] public Text averageDamageDealt;
    [SerializeField] public Text totalDamageRecieved;
    [SerializeField] public Text totalAttacksRecieved;
    [SerializeField] public Text averageDamageRecieved;
    [SerializeField] public Text totalHealingDealt;
    [SerializeField] public Text totalHealsDealt;
    [SerializeField] public Text averageHealDealt;
    [SerializeField] public Text totalHealingRecieved;
    [SerializeField] public Text totalHealsRecieved;
    [SerializeField] public Text averageHealRecieved;

    [SerializeField] public EffectsStatsHolder isProtectedCountRecieved;
    [SerializeField] public EffectsStatsHolder isShieldCountRecieved;
    [SerializeField] public EffectsStatsHolder isStunnedCountRecieved;
    [SerializeField] public EffectsStatsHolder isFrozenCountRecieved;
    [SerializeField] public EffectsStatsHolder isTrappedCountRecieved;
    [SerializeField] public EffectsStatsHolder isMarkedCountRecieved;
    [SerializeField] public EffectsStatsHolder isUnLuckyCountRecieved;
    [SerializeField] public EffectsStatsHolder isLastStandCountRecieved;
    [SerializeField] public EffectsStatsHolder isMadnessCountRecieved;
    [SerializeField] public EffectsStatsHolder isCursedCountRecieved;
    [SerializeField] public EffectsStatsHolder isAttackBoostedCountRecieved;
    [SerializeField] public EffectsStatsHolder isAttackBrokenCountRecieved;
    [SerializeField] public EffectsStatsHolder isDefenseBoostedCountRecieved;
    [SerializeField] public EffectsStatsHolder isDefenseBrokenCountRecieved;
    [SerializeField] public EffectsStatsHolder isSpeedBoostedCountRecieved;
    [SerializeField] public EffectsStatsHolder isSpeedBrokenCountRecieved;
    [SerializeField] public EffectsStatsHolder isAccuracyBoostedCountRecieved;
    [SerializeField] public EffectsStatsHolder isAccuracyBrokenCountRecieved;
    [SerializeField] public EffectsStatsHolder isCritRateBoostedCountRecieved;
    [SerializeField] public EffectsStatsHolder isCritRateBrokenCountRecieved;
    [SerializeField] public EffectsStatsHolder isCritDamageBoostedCountRecieved;
    [SerializeField] public EffectsStatsHolder isCritDamageBrokenCountRecieved;
    [SerializeField] public EffectsStatsHolder isResistenceBoostedCountRecieved;
    [SerializeField] public EffectsStatsHolder isResistenceBrokenCountRecieved;
    [SerializeField] public EffectsStatsHolder brandedCountRecieved;
    [SerializeField] public EffectsStatsHolder isProtectedCountApplied;
    [SerializeField] public EffectsStatsHolder isShieldCountApplied;
    [SerializeField] public EffectsStatsHolder isStunnedCountApplied;
    [SerializeField] public EffectsStatsHolder isFrozenCountApplied;
    [SerializeField] public EffectsStatsHolder isTrappedCountApplied;
    [SerializeField] public EffectsStatsHolder isMarkedCountApplied;
    [SerializeField] public EffectsStatsHolder isUnLuckyCountApplied;
    [SerializeField] public EffectsStatsHolder isLastStandCountApplied;
    [SerializeField] public EffectsStatsHolder isMadnessCountApplied;
    [SerializeField] public EffectsStatsHolder isCursedCountApplied;
    [SerializeField] public EffectsStatsHolder isAttackBoostedCountApplied;
    [SerializeField] public EffectsStatsHolder isAttackBrokenCountApplied;
    [SerializeField] public EffectsStatsHolder isDefenseBoostedCountApplied;
    [SerializeField] public EffectsStatsHolder isDefenseBrokenCountApplied;
    [SerializeField] public EffectsStatsHolder isSpeedBoostedCountApplied;
    [SerializeField] public EffectsStatsHolder isSpeedBrokenCountApplied;
    [SerializeField] public EffectsStatsHolder isAccuracyBoostedCountApplied;
    [SerializeField] public EffectsStatsHolder isAccuracyBrokenCountApplied;
    [SerializeField] public EffectsStatsHolder isCritRateBoostedCountApplied;
    [SerializeField] public EffectsStatsHolder isCritRateBrokenCountApplied;
    [SerializeField] public EffectsStatsHolder isCritDamageBoostedCountApplied;
    [SerializeField] public EffectsStatsHolder isCritDamageBrokenCountApplied;
    [SerializeField] public EffectsStatsHolder isResistenceBoostedCountApplied;
    [SerializeField] public EffectsStatsHolder isResistenceBrokenCountApplied;
    [SerializeField] public EffectsStatsHolder brandedCountApplied;

    public void LoadData(UnitDTO _unitDTO, int teamID, BattleUnitStats _unitStats, BattleController battleController)
    {
        unitName.text = _unitDTO.name;
        unitIcon.HydrateUnitIcon(_unitDTO, UnitSpawner.Instance.database);
        KOs.text = _unitStats.totalKOs.ToString();
        faints.text = _unitStats.faints.ToString();
        debuffsApplied.text = _unitStats.debuffsApplied.ToString();
        buffsApplied.text = _unitStats.buffsApplied.ToString();
        debuffsRecieved.text = _unitStats.debuffsReceived.ToString();
        buffsRecieved.text = _unitStats.buffsReceived.ToString();
        totalDamageDealt.text = _unitStats.totalDamageDealt.ToString("N2");
        totalAttacksDealt.text = _unitStats.attackCountDealt.ToString("N2");
        averageDamageDealt.text = (_unitStats.attackCountDealt == 0 ? 0 : (_unitStats.totalDamageDealt / _unitStats.attackCountDealt)).ToString("N2");
        totalDamageRecieved.text = _unitStats.totalDamageRecieved.ToString("N2");
        totalAttacksRecieved.text = _unitStats.attackCountRecieved.ToString("N2");
        averageDamageRecieved.text = (_unitStats.attackCountRecieved == 0 ? 0 : (_unitStats.totalDamageRecieved / _unitStats.attackCountRecieved)).ToString("N2");
        totalHealingDealt.text = _unitStats.totalHealingDone.ToString("N2");
        totalHealsDealt.text = _unitStats.healingCountDealt.ToString("N2");
        averageHealDealt.text = (_unitStats.healingCountDealt == 0 ? 0 : (_unitStats.totalHealingDone / _unitStats.healingCountDealt)).ToString("N2");
        totalHealingRecieved.text = _unitStats.totalHealingRecieved.ToString("N2");
        totalHealsRecieved.text = _unitStats.healingCountRecieved.ToString("N2");
        averageHealRecieved.text = (_unitStats.healingCountRecieved == 0 ? 0 : (_unitStats.totalHealingRecieved / _unitStats.healingCountRecieved)).ToString("N2");

        isProtectedCountRecieved.loadAmount(_unitStats.isProtectedCountRecieved, (_unitStats.isProtectedCountRecieved >= battleController.unitBattleStats[teamID].isProtectedCountRecievedMax && _unitStats.isProtectedCountRecieved != 0 ? Color.yellow : Color.white));
        isShieldCountRecieved.loadAmount(_unitStats.isShieldCountRecieved, (_unitStats.isShieldCountRecieved >= battleController.unitBattleStats[teamID].isShieldCountRecievedMax && _unitStats.isShieldCountRecieved != 0 ? Color.yellow : Color.white));
        isStunnedCountRecieved.loadAmount(_unitStats.isStunnedCountRecieved, (_unitStats.isStunnedCountRecieved >= battleController.unitBattleStats[teamID].isStunnedCountRecievedMax && _unitStats.isStunnedCountRecieved != 0 ? Color.yellow : Color.white));
        isFrozenCountRecieved.loadAmount(_unitStats.isFrozenCountRecieved, (_unitStats.isFrozenCountRecieved >= battleController.unitBattleStats[teamID].isFrozenCountRecievedMax && _unitStats.isFrozenCountRecieved != 0 ? Color.yellow : Color.white));
        isTrappedCountRecieved.loadAmount(_unitStats.isTrappedCountRecieved, (_unitStats.isTrappedCountRecieved >= battleController.unitBattleStats[teamID].isTrappedCountRecievedMax && _unitStats.isTrappedCountRecieved != 0 ? Color.yellow : Color.white));
        isMarkedCountRecieved.loadAmount(_unitStats.isMarkedCountRecieved, (_unitStats.isMarkedCountRecieved >= battleController.unitBattleStats[teamID].isMarkedCountRecievedMax && _unitStats.isMarkedCountRecieved != 0 ? Color.yellow : Color.white));
        isUnLuckyCountRecieved.loadAmount(_unitStats.isUnLuckyCountRecieved, (_unitStats.isUnLuckyCountRecieved >= battleController.unitBattleStats[teamID].isUnLuckyCountRecievedMax && _unitStats.isUnLuckyCountRecieved != 0 ? Color.yellow : Color.white));
        isLastStandCountRecieved.loadAmount(_unitStats.isLastStandCountRecieved, (_unitStats.isLastStandCountRecieved >= battleController.unitBattleStats[teamID].isLastStandCountRecievedMax && _unitStats.isLastStandCountRecieved != 0 ? Color.yellow : Color.white));
        isMadnessCountRecieved.loadAmount(_unitStats.isMadnessCountRecieved, (_unitStats.isMadnessCountRecieved >= battleController.unitBattleStats[teamID].isMadnessCountRecievedMax && _unitStats.isMadnessCountRecieved != 0 ? Color.yellow : Color.white));
        isCursedCountRecieved.loadAmount(_unitStats.isCursedCountRecieved, (_unitStats.isCursedCountRecieved >= battleController.unitBattleStats[teamID].isCursedCountRecievedMax && _unitStats.isCursedCountRecieved != 0 ? Color.yellow : Color.white));
        isAttackBoostedCountRecieved.loadAmount(_unitStats.isAttackBoostedCountRecieved, (_unitStats.isAttackBoostedCountRecieved >= battleController.unitBattleStats[teamID].isAttackBoostedCountRecievedMax && _unitStats.isAttackBoostedCountRecieved != 0 ? Color.yellow : Color.white));
        isAttackBrokenCountRecieved.loadAmount(_unitStats.isAttackBrokenCountRecieved, (_unitStats.isAttackBrokenCountRecieved >= battleController.unitBattleStats[teamID].isAttackBrokenCountRecievedMax && _unitStats.isAttackBrokenCountRecieved != 0 ? Color.yellow : Color.white));
        isDefenseBoostedCountRecieved.loadAmount(_unitStats.isDefenseBoostedCountRecieved, (_unitStats.isDefenseBoostedCountRecieved >= battleController.unitBattleStats[teamID].isDefenseBoostedCountRecievedMax && _unitStats.isDefenseBoostedCountRecieved != 0 ? Color.yellow : Color.white));
        isDefenseBrokenCountRecieved.loadAmount(_unitStats.isDefenseBrokenCountRecieved, (_unitStats.isDefenseBrokenCountRecieved >= battleController.unitBattleStats[teamID].isDefenseBrokenCountRecievedMax && _unitStats.isDefenseBrokenCountRecieved != 0 ? Color.yellow : Color.white));
        isSpeedBoostedCountRecieved.loadAmount(_unitStats.isSpeedBoostedCountRecieved, (_unitStats.isSpeedBoostedCountRecieved >= battleController.unitBattleStats[teamID].isSpeedBoostedCountRecievedMax && _unitStats.isSpeedBoostedCountRecieved != 0 ? Color.yellow : Color.white));
        isSpeedBrokenCountRecieved.loadAmount(_unitStats.isSpeedBrokenCountRecieved, (_unitStats.isSpeedBrokenCountRecieved >= battleController.unitBattleStats[teamID].isSpeedBrokenCountRecievedMax && _unitStats.isSpeedBrokenCountRecieved != 0 ? Color.yellow : Color.white));
        isAccuracyBoostedCountRecieved.loadAmount(_unitStats.isAccuracyBoostedCountRecieved, (_unitStats.isAccuracyBoostedCountRecieved >= battleController.unitBattleStats[teamID].isAccuracyBoostedCountRecievedMax && _unitStats.isAccuracyBoostedCountRecieved != 0 ? Color.yellow : Color.white));
        isAccuracyBrokenCountRecieved.loadAmount(_unitStats.isAccuracyBrokenCountRecieved, (_unitStats.isAccuracyBrokenCountRecieved >= battleController.unitBattleStats[teamID].isAccuracyBrokenCountRecievedMax && _unitStats.isAccuracyBrokenCountRecieved != 0 ? Color.yellow : Color.white));
        isCritRateBoostedCountRecieved.loadAmount(_unitStats.isCritRateBoostedCountRecieved, (_unitStats.isCritRateBoostedCountRecieved >= battleController.unitBattleStats[teamID].isCritRateBoostedCountRecievedMax && _unitStats.isCritRateBoostedCountRecieved != 0 ? Color.yellow : Color.white));
        isCritRateBrokenCountRecieved.loadAmount(_unitStats.isCritRateBrokenCountRecieved, (_unitStats.isCritRateBrokenCountRecieved >= battleController.unitBattleStats[teamID].isCritRateBrokenCountRecievedMax && _unitStats.isCritRateBrokenCountRecieved != 0 ? Color.yellow : Color.white));
        isCritDamageBoostedCountRecieved.loadAmount(_unitStats.isCritDamageBoostedCountRecieved, (_unitStats.isCritDamageBoostedCountRecieved >= battleController.unitBattleStats[teamID].isCritDamageBoostedCountRecievedMax && _unitStats.isCritDamageBoostedCountRecieved != 0 ? Color.yellow : Color.white));
        isCritDamageBrokenCountRecieved.loadAmount(_unitStats.isCritDamageBrokenCountRecieved, (_unitStats.isCritDamageBrokenCountRecieved >= battleController.unitBattleStats[teamID].isCritDamageBrokenCountRecievedMax && _unitStats.isCritDamageBrokenCountRecieved != 0 ? Color.yellow : Color.white));
        isResistenceBoostedCountRecieved.loadAmount(_unitStats.isResistenceBoostedCountRecieved, (_unitStats.isResistenceBoostedCountRecieved >= battleController.unitBattleStats[teamID].isResistenceBoostedCountRecievedMax && _unitStats.isResistenceBoostedCountRecieved != 0 ? Color.yellow : Color.white));
        isResistenceBrokenCountRecieved.loadAmount(_unitStats.isResistenceBrokenCountRecieved, (_unitStats.isResistenceBrokenCountRecieved >= battleController.unitBattleStats[teamID].isResistenceBrokenCountRecievedMax && _unitStats.isResistenceBrokenCountRecieved != 0 ? Color.yellow : Color.white));
        brandedCountRecieved.loadAmount(_unitStats.brandedCountRecieved, (_unitStats.brandedCountRecieved >= battleController.unitBattleStats[teamID].brandedCountRecievedMax && _unitStats.brandedCountRecieved != 0 ? Color.yellow : Color.white));

        isProtectedCountApplied.loadAmount(_unitStats.isProtectedCountApplied, (_unitStats.isProtectedCountApplied >= battleController.unitBattleStats[teamID].isProtectedCountAppliedMax && _unitStats.isProtectedCountApplied != 0 ? Color.yellow : Color.white));
        isShieldCountApplied.loadAmount(_unitStats.isShieldCountApplied, (_unitStats.isShieldCountApplied >= battleController.unitBattleStats[teamID].isShieldCountAppliedMax && _unitStats.isShieldCountApplied != 0 ? Color.yellow : Color.white));
        isStunnedCountApplied.loadAmount(_unitStats.isStunnedCountApplied, (_unitStats.isStunnedCountApplied >= battleController.unitBattleStats[teamID].isStunnedCountAppliedMax && _unitStats.isStunnedCountApplied != 0 ? Color.yellow : Color.white));
        isFrozenCountApplied.loadAmount(_unitStats.isFrozenCountApplied, (_unitStats.isFrozenCountApplied >= battleController.unitBattleStats[teamID].isFrozenCountAppliedMax && _unitStats.isFrozenCountApplied != 0 ? Color.yellow : Color.white));
        isTrappedCountApplied.loadAmount(_unitStats.isTrappedCountApplied, (_unitStats.isTrappedCountApplied >= battleController.unitBattleStats[teamID].isTrappedCountAppliedMax && _unitStats.isTrappedCountApplied != 0 ? Color.yellow : Color.white));
        isMarkedCountApplied.loadAmount(_unitStats.isMarkedCountApplied, (_unitStats.isMarkedCountApplied >= battleController.unitBattleStats[teamID].isMarkedCountAppliedMax && _unitStats.isMarkedCountApplied != 0 ? Color.yellow : Color.white));
        isUnLuckyCountApplied.loadAmount(_unitStats.isUnLuckyCountApplied, (_unitStats.isUnLuckyCountApplied >= battleController.unitBattleStats[teamID].isUnLuckyCountAppliedMax && _unitStats.isUnLuckyCountApplied != 0 ? Color.yellow : Color.white));
        isLastStandCountApplied.loadAmount(_unitStats.isLastStandCountApplied, (_unitStats.isLastStandCountApplied >= battleController.unitBattleStats[teamID].isLastStandCountAppliedMax && _unitStats.isLastStandCountApplied != 0 ? Color.yellow : Color.white));
        isMadnessCountApplied.loadAmount(_unitStats.isMadnessCountApplied, (_unitStats.isMadnessCountApplied >= battleController.unitBattleStats[teamID].isMadnessCountAppliedMax && _unitStats.isMadnessCountApplied != 0 ? Color.yellow : Color.white));
        isCursedCountApplied.loadAmount(_unitStats.isCursedCountApplied, (_unitStats.isCursedCountApplied >= battleController.unitBattleStats[teamID].isCursedCountAppliedMax && _unitStats.isCursedCountApplied != 0 ? Color.yellow : Color.white));
        isAttackBoostedCountApplied.loadAmount(_unitStats.isAttackBoostedCountApplied, (_unitStats.isAttackBoostedCountApplied >= battleController.unitBattleStats[teamID].isAttackBoostedCountAppliedMax && _unitStats.isAttackBoostedCountApplied != 0 ? Color.yellow : Color.white));
        isAttackBrokenCountApplied.loadAmount(_unitStats.isAttackBrokenCountApplied, (_unitStats.isAttackBrokenCountApplied >= battleController.unitBattleStats[teamID].isAttackBrokenCountAppliedMax && _unitStats.isAttackBrokenCountApplied != 0 ? Color.yellow : Color.white));
        isDefenseBoostedCountApplied.loadAmount(_unitStats.isDefenseBoostedCountApplied, (_unitStats.isDefenseBoostedCountApplied >= battleController.unitBattleStats[teamID].isDefenseBoostedCountAppliedMax && _unitStats.isDefenseBoostedCountApplied != 0 ? Color.yellow : Color.white));
        isDefenseBrokenCountApplied.loadAmount(_unitStats.isDefenseBrokenCountApplied, (_unitStats.isDefenseBrokenCountApplied >= battleController.unitBattleStats[teamID].isDefenseBrokenCountAppliedMax && _unitStats.isDefenseBrokenCountApplied != 0 ? Color.yellow : Color.white));
        isSpeedBoostedCountApplied.loadAmount(_unitStats.isSpeedBoostedCountApplied, (_unitStats.isSpeedBoostedCountApplied >= battleController.unitBattleStats[teamID].isSpeedBoostedCountAppliedMax && _unitStats.isSpeedBoostedCountApplied != 0 ? Color.yellow : Color.white));
        isSpeedBrokenCountApplied.loadAmount(_unitStats.isSpeedBrokenCountApplied, (_unitStats.isSpeedBrokenCountApplied >= battleController.unitBattleStats[teamID].isSpeedBrokenCountAppliedMax && _unitStats.isSpeedBrokenCountApplied != 0 ? Color.yellow : Color.white));
        isAccuracyBoostedCountApplied.loadAmount(_unitStats.isAccuracyBoostedCountApplied, (_unitStats.isAccuracyBoostedCountApplied >= battleController.unitBattleStats[teamID].isAccuracyBoostedCountAppliedMax && _unitStats.isAccuracyBoostedCountApplied != 0 ? Color.yellow : Color.white));
        isAccuracyBrokenCountApplied.loadAmount(_unitStats.isAccuracyBrokenCountApplied, (_unitStats.isAccuracyBrokenCountApplied >= battleController.unitBattleStats[teamID].isAccuracyBrokenCountAppliedMax && _unitStats.isAccuracyBrokenCountApplied != 0 ? Color.yellow : Color.white));
        isCritRateBoostedCountApplied.loadAmount(_unitStats.isCritRateBoostedCountApplied, (_unitStats.isCritRateBoostedCountApplied >= battleController.unitBattleStats[teamID].isCritRateBoostedCountAppliedMax && _unitStats.isCritRateBoostedCountApplied != 0 ? Color.yellow : Color.white));
        isCritRateBrokenCountApplied.loadAmount(_unitStats.isCritRateBrokenCountApplied, (_unitStats.isCritRateBrokenCountApplied >= battleController.unitBattleStats[teamID].isCritRateBrokenCountAppliedMax && _unitStats.isCritRateBrokenCountApplied != 0 ? Color.yellow : Color.white));
        isCritDamageBoostedCountApplied.loadAmount(_unitStats.isCritDamageBoostedCountApplied, (_unitStats.isCritDamageBoostedCountApplied >= battleController.unitBattleStats[teamID].isCritDamageBoostedCountAppliedMax && _unitStats.isCritDamageBoostedCountApplied != 0 ? Color.yellow : Color.white));
        isCritDamageBrokenCountApplied.loadAmount(_unitStats.isCritDamageBrokenCountApplied, (_unitStats.isCritDamageBrokenCountApplied >= battleController.unitBattleStats[teamID].isCritDamageBrokenCountAppliedMax && _unitStats.isCritDamageBrokenCountApplied != 0 ? Color.yellow : Color.white));
        isResistenceBoostedCountApplied.loadAmount(_unitStats.isResistenceBoostedCountApplied, (_unitStats.isResistenceBoostedCountApplied >= battleController.unitBattleStats[teamID].isResistenceBoostedCountAppliedMax && _unitStats.isResistenceBoostedCountApplied != 0 ? Color.yellow : Color.white));
        isResistenceBrokenCountApplied.loadAmount(_unitStats.isResistenceBrokenCountApplied, (_unitStats.isResistenceBrokenCountApplied >= battleController.unitBattleStats[teamID].isResistenceBrokenCountAppliedMax && _unitStats.isResistenceBrokenCountApplied != 0 ? Color.yellow : Color.white));
        brandedCountApplied.loadAmount(_unitStats.brandedCountApplied, (_unitStats.brandedCountApplied >= battleController.unitBattleStats[teamID].brandedCountAppliedMax && _unitStats.brandedCountApplied != 0 ? Color.yellow : Color.white));
    }
}
