using System.Collections.Generic;
using CapsuleWars.Core;
using UnityEngine;

namespace CapsuleWars.Data.Units
{
    /// <summary>
    /// A single swappable part (body shape, hand variant, foot variant, head prop).
    /// Holds the mesh and a default material set; palette tinting is applied
    /// at runtime by UnitCustomization based on the slot mount's PaletteRole.
    /// </summary>
    [CreateAssetMenu(fileName = "BodyPart", menuName = "CapsuleWars/Body Part", order = 10)]
    public class BodyPart_SO : ScriptableObject
    {
        [Tooltip("Stable ID used by save files and the Database lookup.")]
        [SerializeField] private string partId;

        [Tooltip("I2 term key for the part's display name (e.g. Part.Hand.CrabClaw.Name).")]
        [SerializeField] private string nameTermKey;

        [Tooltip("Which slot this part is allowed to be assigned to.")]
        [SerializeField] private PartSlot slot = PartSlot.Body;

        [Tooltip("Mesh applied to the slot's MeshFilter at spawn time.")]
        [SerializeField] private Mesh mesh;

        [Tooltip("Default materials. UnitCustomization may override _BaseColor via the palette.")]
        [SerializeField] private Material[] defaultMaterials;

        [Tooltip("UI icon shown in the customization bag/slots. Generated by Tools/Icons or hand-assigned.")]
        [SerializeField] private Sprite icon;

        [Header("Eyes (head parts only — per-race placement)")]
        [Tooltip("Head parts only: enable so the two eyes are kept pattern-free and get their own color.")]
        [SerializeField] private bool hasEyes;
        [Tooltip("Eye placement in the mesh's LOCAL space: x = half-spread between the eyes, y = height from center, z = depth toward the face.")]
        [SerializeField] private Vector3 eyeOffset = new Vector3(0.12f, 0.06f, 0.22f);
        [Tooltip("Radius of each eye region (local space).")]
        [SerializeField] private float eyeRadius = 0.08f;
        [Tooltip("Default eye color (overridable in the Unit Builder).")]
        [SerializeField] private Color eyeColor = new Color(0.85f, 0.72f, 0.20f);

        public string PartId => partId;
        public string NameTermKey => nameTermKey;
        public PartSlot Slot => slot;
        public Mesh Mesh => mesh;
        public IReadOnlyList<Material> DefaultMaterials => defaultMaterials;
        public Sprite Icon => icon;
        public bool HasEyes => hasEyes;
        public Vector3 EyeOffset => eyeOffset;
        public float EyeRadius => eyeRadius;
        public Color EyeColor => eyeColor;
    }
}
