using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class UnitNameGenerator
{
    List<string> names = new List<string>()
    {
        "Achilles",
        "Hector",
        "Leonidas",
        "Alexander",
        "Julius",
        "Caesar",
        "Hannibal",
        "Sun Tzu",
        "Ramses",
        "Cyrus",
        "Attila",
        "Charlemagne",
        "Richard",
        "Lionheart",
        "William",
        "Genghis",
        "Saladin",
        "El Cid",
        "Vlad",
        "Impaler",
        "Joan",
        "Wallace",
        "Edward",
        "Black Prince",
        "Minamoto",
        "Yoshitsune",
        "Miyamoto",
        "Musashi",
        "Tomoe",
        "Gozen",
        "Takeda",
        "Shingen",
        "Oda",
        "Nobunaga",
        "Guan Yu",
        "Zhao Yun",
        "Zheng",
        "Chenggong",
        "Koxinga",
        "Nurhaci",
        "Ragnar",
        "Bjorn",
        "Ironside",
        "Harald",
        "Erik",
        "Leif",
        "Ivar",
        "Boneless",
        "Sigurd",
        "Snake Eye",
        "Olaf",
        "Canute",
        "Halfdan",
        "Shaka",
        "Hannibal",
        "Queen",
        "Amina",
        "Behanzin",
        "Almamy",
        "Asantewaa",
        "Taharqa",
        "Nzinga",
        "Sundjata",
        "Cetshwayo",
        "Sitting Bull",
        "Crazy Horse",
        "Geronimo",
        "Tecumseh",
        "Red Cloud",
        "Cochise",
        "Chief Joseph",
        "Black Hawk",
        "Osceola",
        "Pontiac",
        "Al-Mansur",
        "Khalid",
        "Timur",
        "Baybars",
        "Nader Shah",
        "Cyrus",
        "Al-Kindi",
        "Selim I",
        "Tamerlane",
        "Malik",
        "Godfrey",
        "Baldwin",
        "Bertrand",
        "Rodrigo",
        "Simon",
        "Tancred",
        "Robert",
        "Bruce",
        "Henry",
        "John",
        "Bertrand",
        "George",
        "Napoleon",
        "Bonaparte",
        "Simon", 
        "Bolivar",
        "Giuseppe",
        "Garibaldi",
        "Bismarck",
        "Toussaint",
        "Louverture",
        "Che Guevara",
        "Giap",
        "Isoroku",
        "Yamamoto",
        "Erwin",
        "Rommel",
        "Arthur",
        "Beowulf",
        "Cú Chulainn",
        "Siegfried",
        "Heracles",
        "Perseus",
        "Theseus",
        "Gilgamesh",
        "Rostam",
        "Lancelot"

    };
    
    public UnitNameGenerator() { }

    public string GetName()
    {
        return names[Random.Range(0, names.Count)];
    }
    
}
